[simulation]
name = "debris_impact_demo"
et_start_s = 306547266.1824111
duration_s = 10800.0

[debris]
am_srp = 0.02
Cr = 1.3

[initial_state]
frame = "central_inertial"
position_km = [0.0, 2000.0, 0.0]
velocity_kms = [0.0, 0.0, 1.501]

[force_model]
central_body = "Moon"
harmonics_file = "../../external/spody-core/raw_data/GRGM1200B/gggrx_1200b_sha.tab"
harmonics_degree = 20
third_bodies = ["Sun", "Earth"]
srp = true

[ephemeris]
file = "../../external/spody-core/raw_data/DE440/de440.spody"

[integrator]
type = "rkdp45"
rel_tol = 1e-09
h_init_s = 60.0
h_min_s = 1e-05
h_max_s = 600.0

[output]
mode = "fixed"
interval_s = 30.0
output_dir = "output"
bin_file = "output/debris_impact_demo_state_icrf.bin"
events_log = "output/debris_impact_demo_events.bin"

[events]
eclipse_threshold = 0.5

[batch]
name = "debris_impact_demo"
output_dir = "output"
thread_number = 4
cases_file = "cases_impact.csv"
cases_frame = "icrf"
cases_source_file = "cases_impact.csv"

[batch.columns]
Cr = "debris.Cr"
am_srp = "debris.am_srp"
dr_x_km = { target = "initial_state.position_km[0]", mode = "delta" }
dr_y_km = { target = "initial_state.position_km[1]", mode = "delta" }
dr_z_km = { target = "initial_state.position_km[2]", mode = "delta" }
dv_x_kms = { target = "initial_state.velocity_kms[0]", mode = "delta" }
dv_y_kms = { target = "initial_state.velocity_kms[1]", mode = "delta" }
dv_z_kms = { target = "initial_state.velocity_kms[2]", mode = "delta" }
