# PyInstaller spec for the SpOdy desktop bundle.
#
# Build with:
#   python build_bundle.py
# (or the equivalent: pyinstaller --noconfirm spody_gui.spec)
#
# *** One-folder, NOT one-file. ***
# The wizard's "data dir" defaults to <sys.executable>/data so a
# distributable bundle stays portable: zip the folder, ship it, the
# data dir lands next to the exe at the user's chosen location. With
# --onefile, sys.executable points at PyInstaller's per-launch temp
# extraction dir and the wizard would download into a folder that
# gets wiped on next launch.
#
# Heavy deps (PySide6 + VTK + matplotlib + numpy) come from
# PyInstaller's built-in hooks; we just nudge a couple of VTK
# submodules that aren't auto-detected.

from PyInstaller.utils.hooks import collect_submodules

# The Qt/VTK integration module isn't picked up by VTK's default hook,
# nor is numpy_support which we use in vtk_canvas. Collecting the whole
# vtkmodules subtree is heavier than necessary but harmless and makes
# the bundle robust against future GUI code adding more VTK calls.
vtk_hidden = [
    "vtkmodules.qt.QVTKRenderWindowInteractor",
    "vtkmodules.util.numpy_support",
]
vtk_hidden += collect_submodules("vtkmodules")

# Datas: (source-on-disk, destination-inside-bundle). Paths are
# relative to the spec file's directory (python/). The examples
# directory is one level up under the repo root.
datas = [
    # Ship the example TOMLs (no output/ subdirs -- those are
    # regenerated by spody at run time and just bloat the bundle).
    ("../examples/README.md",                "examples"),
    ("../examples/batch_demo/input.toml",    "examples/batch_demo"),
    ("../examples/batch_demo/cases.csv",     "examples/batch_demo"),
    ("../examples/batch_demo/README.md",     "examples/batch_demo"),
    ("../examples/debris_demo/input.toml",   "examples/debris_demo"),
    ("../examples/debris_demo/cases.csv",    "examples/debris_demo"),
    ("../examples/debris_demo/README.md",    "examples/debris_demo"),
    ("../examples/lro_6day/input.toml",      "examples/lro_6day"),
    ("../examples/lro_6day/README.md",       "examples/lro_6day"),
]

# Drop modules we know we don't ship. tkinter ships with Python but
# matplotlib's QtAgg backend doesn't need it; excluding shaves ~15 MB.
excludes = [
    "tkinter",
    "_tkinter",
    "PyQt5",
    "PyQt6",
]


a = Analysis(
    ["run_spody_gui.py"],
    pathex=["."],
    binaries=[],
    datas=datas,
    hiddenimports=vtk_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="spody-gui",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                # UPX often trips antivirus heuristics
    console=False,            # windowed app: no extra cmd window
                              # (flip to True to see Python tracebacks
                              # when the bundle crashes on startup)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,                # placeholder -- ship .ico when available
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="spody-gui",
)
