# Copyright 2026 ValeEng
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# PyInstaller spec for the SpOdy desktop bundle.
#
# Build with:
#   python build_bundle.py
# (or the equivalent: pyinstaller --noconfirm spody_gui.spec)
#
# *** One-folder, NOT one-file. ***
# The wizard's "data dir" defaults to <sys.executable>/data so a
# distributable bundle stays portable: zip the folder, ship it, the
# data dir lands next to the exe at the user's chosen location. With
# --onefile, sys.executable points at PyInstaller's per-launch temp
# extraction dir and the wizard would download into a folder that
# gets wiped on next launch.
#
# Heavy deps (PySide6 + VTK + matplotlib + numpy) come from
# PyInstaller's built-in hooks; we just nudge a couple of VTK
# submodules that aren't auto-detected.

# Explicit list of VTK modules we actually import (directly or via
# side-effect) -- see vtk_canvas.py for the static imports. The
# alternative `collect_submodules("vtkmodules")` pulls in the whole
# subtree (VR / Web / GTK,Wx,Tk bindings / dozens of exotic IO
# readers for Cesium3DTiles, CGNS, FLUENT, Exodus, EnSight, NetCDF,
# Xdmf2, VTKm GPU accelerators, ...) -- adds ~800 MB of dead weight
# to the macOS / Linux bundle, removing it here is the single
# biggest size win we can do without pruning per-file.
#
# Transitive VTK deps (vtkCommonExecutionModel, vtkRenderingContext2D,
# vtkImagingCore, ...) are pulled in automatically by the per-module
# PyInstaller hooks in _pyinstaller_hooks_contrib once we declare
# the top-level imports below.
vtk_hidden = [
    # vtk_canvas.py uses the Qt integration class which PyInstaller's
    # static analysis can miss because of how it's lazy-imported.
    "vtkmodules.qt.QVTKRenderWindowInteractor",
    # Bridge between numpy arrays and vtk arrays; we use it in
    # set_central_body_texture / add_trajectory.
    "vtkmodules.util.numpy_support",
    # The two side-effect imports in vtk_canvas.py (no symbols used,
    # but loading the module registers the OpenGL / FreeType backends
    # with vtkRenderingCore). Listed explicitly so PyInstaller's
    # tree-shaking can't drop them.
    "vtkmodules.vtkRenderingOpenGL2",
    "vtkmodules.vtkRenderingFreeType",
]

# Datas: (source-on-disk, destination-inside-bundle). Paths are
# relative to the spec file's directory (python/). The examples
# directory is one level up under the repo root.
datas = [
    # Ship the example TOMLs (no output/ subdirs -- those are
    # regenerated by spody at run time and just bloat the bundle).
    ("../examples/README.md",                "examples"),
    ("../examples/batch_demo/input.toml",    "examples/batch_demo"),
    ("../examples/batch_demo/cases.csv",     "examples/batch_demo"),
    ("../examples/batch_demo/README.md",     "examples/batch_demo"),
    ("../examples/debris_demo/input.toml",   "examples/debris_demo"),
    ("../examples/debris_demo/cases.csv",    "examples/debris_demo"),
    ("../examples/debris_demo/README.md",    "examples/debris_demo"),
    ("../examples/lro_6day/input.toml",      "examples/lro_6day"),
    ("../examples/lro_6day/README.md",       "examples/lro_6day"),
]

# User manual PDF -- shipped under docs/ next to spody-gui.exe so
# Help > User manual finds it. Included conditionally: if the PDF
# has not been (re)built, the bundle still builds but the menu
# entry shows a 'not found' dialog. build_bundle.py rebuilds the
# PDF before invoking PyInstaller so this path is normally present.
import os as _os
_pdf = "../docs/user-manual/spody-user-manual.pdf"
if _os.path.isfile(_pdf):
    datas.append((_pdf, "docs"))

# Drop modules we know we don't ship. tkinter ships with Python but
# matplotlib's QtAgg backend doesn't need it; excluding shaves ~15 MB.
excludes = [
    "tkinter",
    "_tkinter",
    "PyQt5",
    "PyQt6",
]

# Windows apiset shims that PyInstaller's auto-analysis sometimes
# misses on Win Server runners. python311.dll imports
# api-ms-win-core-path-l1-1-0.dll; the build runner has it in
# System32 so PyInstaller classifies it as 'OS shim, don't bundle'.
# Some end-user Win10 builds lack that exact shim and the bundle
# then fails at LoadLibrary(python311.dll) with a generic
# 'access to invalid memory location' dialog. Force-include the
# whole api-ms-win-core/crt set from System32 so the bundle is
# self-contained regardless of the target Win10 patch level.
import glob as _glob, os as _os
_extra_binaries = []
if _os.name == "nt":
    _sys32 = _os.path.join(_os.environ.get("WINDIR", r"C:\Windows"), "System32")
    for _pat in ("api-ms-win-core-*.dll", "api-ms-win-crt-*.dll"):
        for _dll in _glob.glob(_os.path.join(_sys32, _pat)):
            _extra_binaries.append((_dll, "."))


a = Analysis(
    ["run_spody_gui.py"],
    pathex=["."],
    binaries=_extra_binaries,
    datas=datas,
    hiddenimports=vtk_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="spody-gui",
    debug=False,
    bootloader_ignore_signals=False,
    # strip=True asks PyInstaller to run `strip` on the bundled
    # binaries (ELF on Linux, Mach-O on macOS). Big win on those
    # OSes because PySide6 / VTK ship with full debug symbols in
    # the wheel -- bundle shrinks ~30..50%. No-op on Windows (PE
    # debug info already external).
    strip=True,
    upx=False,                # UPX often trips antivirus heuristics
    console=True,             # DEBUG: temporarily True so the CI build
                              # surfaces Python tracebacks instead of a
                              # generic 'Failed to load Python DLL' dialog.
                              # Flip back to False before the next real tag.
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,                # placeholder -- ship .ico when available
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=True,               # same rationale as EXE.strip above
    upx=False,
    upx_exclude=[],
    name="spody-gui",
)
